# Generated by Django 2.1.3 on 2018-12-09 17:30

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_photo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=myapp.models.get_image_path, verbose_name='画像'),
        ),
    ]
