# Generated by Django 2.1.3 on 2018-12-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alcohol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
