# Generated by Django 2.1.3 on 2018-12-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_infouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infouser',
            name='nickname',
        ),
    ]
